name: firmanager-frontend
static_sites:
  - name: firmanager
    github:
      repo: ballebp/firmanager-emergent2
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    output_dir: /build
    catchall_document: index.html
    routes:
      - path: /
    envs:
      - key: REACT_APP_BACKEND_URL
        value: "https://firmanager-backend.onrender.com"
